version: '3.8'
services:
  mariadb:
    image: mariadb:10.11
    container_name: mleczna-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Filipinka2025
      MYSQL_DATABASE: MleczDroga
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - "5001:3306"
    volumes:
      - ./database-server/mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
