name: Build and Publish Docker Image

# Kiedy uruchomić? Przy każdym wypchnięciu (push) na gałąź 'main'
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Pozwala też uruchomić ręcznie przyciskiem

env:
  REGISTRY: ghcr.io
  # Nazwa obrazu: ghcr.io/twoj-login/nazwa-repo
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Pozwolenie na zapisywanie paczki

    steps:
      - name: Pobranie kodu (Checkout)
        uses: actions/checkout@v4

      - name: Logowanie do GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Przygotowanie metadanych (tagi)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Zbudowanie i wypchnięcie obrazu (Build & Push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}